server:
  port: 8081

spring:
  application:
    name: bank-cards-management
  
  # Database Configuration - MySQL (как в вашем проекте)
  datasource:
    url: jdbc:mysql://localhost:3306/bankcards?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: BankCardsPool

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 15
        order_inserts: true
        generate_statistics: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # Multipart Configuration
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  # Freemarker Configuration
  freemarker:
    expose-request-attributes: true

  # Liquibase Configuration
  liquibase:
    enabled: false
    contexts: default
    change-log: classpath:db/migration/changelog.xml

  # Security Configuration
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# JWT Configuration (как в вашем проекте)
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging Configuration
logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
